<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>my_robot_bringup</name>
  <version>0.1.0</version>
  <description>Launch files tying TurtleBot3 simulation + custom control nodes together.</description>
  <maintainer email="you@example.com">Mahdi Yousef</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>turtlebot3_gazebo</exec_depend>
  <exec_depend>turtlebot3_navigation2</exec_depend>
  <exec_depend>turtlebot3_cartographer</exec_depend>
  <exec_depend>my_robot_control</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
